version: 2

models:
    - name: rpt_hires
      columns: 
        - name: unique_key
          tests:
            - not_null
            - unique

    - name: rpt_job_opening_interviews
      tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - job_id
              - job_opening_id
              - application_id
              - scheduled_interview_id

    - name: rpt_job_opening_stage
      tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - job_id
              - job_opening_id
              - application_id
              - stage_entered_date 